"""OpenMandate Python SDK — programmatic access to OpenMandate."""

from ._client import AsyncOpenMandate, OpenMandate
from ._exceptions import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    OpenMandateError,
    PermissionDeniedError,
    RateLimitError,
    ValidationError,
)
from ._pagination import AsyncPage, SyncPage
from ._version import __version__
from .resources.contacts import AsyncContacts, Contacts
from .types import (
    AddContactParams,
    AnswerParam,
    CloseReason,
    Compatibility,
    Concern,
    Contact,
    ContactType,
    CorrectionParam,
    IntakeAnswer,
    Mandate,
    MandateCreateParams,
    MandateListParams,
    MandateStatus,
    MandateSubmitAnswersParams,
    Match,
    MatchListParams,
    MatchOutcome,
    MatchStatus,
    Question,
    QuestionConstraints,
    QuestionOption,
    Strength,
    UpdateContactParams,
    VerificationStatus,
    VerifiedContact,
    VerifyContactParams,
)

__all__ = [
    # Client
    "AsyncOpenMandate",
    "OpenMandate",
    # Exceptions
    "APIConnectionError",
    "APIError",
    "APITimeoutError",
    "AuthenticationError",
    "BadRequestError",
    "ConflictError",
    "InternalServerError",
    "NotFoundError",
    "OpenMandateError",
    "PermissionDeniedError",
    "RateLimitError",
    "ValidationError",
    # Pagination
    "AsyncPage",
    "SyncPage",
    # Version
    "__version__",
    # Resources
    "AsyncContacts",
    "Contacts",
    # Types
    "AddContactParams",
    "AnswerParam",
    "CloseReason",
    "Compatibility",
    "Concern",
    "Contact",
    "ContactType",
    "CorrectionParam",
    "IntakeAnswer",
    "Mandate",
    "MandateCreateParams",
    "MandateListParams",
    "MandateStatus",
    "MandateSubmitAnswersParams",
    "Match",
    "MatchListParams",
    "MatchOutcome",
    "MatchStatus",
    "Question",
    "QuestionConstraints",
    "QuestionOption",
    "Strength",
    "UpdateContactParams",
    "VerificationStatus",
    "VerifiedContact",
    "VerifyContactParams",
]
